#!/usr/bin/env bash
# OPTIONAL — make BuildUp fully offline on the very first load by self-hosting the fonts.
# Downloads Fredoka + Nunito woff2 from google-webfonts-helper and writes fonts/fonts.css.
# Until you run this, the app loads fonts from Google's CDN (cached by the SW after visit 1).
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p fonts

API="https://gwfh.mranftl.com/api/fonts"

dl() { # dl <font-id> <weights>
  local id="$1" weights="$2"
  echo "fetching $id ($weights)…"
  curl -fsSL "$API/$id?download=zip&subsets=latin&variants=$weights&formats=woff2" -o "fonts/$id.zip"
  ( cd fonts && unzip -oq "$id.zip" && rm "$id.zip" )
}

dl fredoka "400,500,600,700"
dl nunito  "400,600,700,800"

{
  echo "/* self-hosted — generated by scripts/fetch-fonts.sh */"
  for f in fonts/*.woff2; do
    base=$(basename "$f" .woff2)
    fam=$(echo "$base" | sed -E 's/-.*//; s/^./\U&/')
    wt=$(echo "$base" | grep -oE '[0-9]{3}' || echo 400)
    printf '@font-face{font-family:"%s";font-style:normal;font-weight:%s;font-display:swap;src:url("./%s") format("woff2");}\n' \
      "$fam" "$wt" "$(basename "$f")"
  done
} > fonts/fonts.css

cat <<'NOTE'

Done. To switch the app to self-hosted fonts:
  1. In index.html, replace the Google Fonts <link> with:
       <link rel="stylesheet" href="./fonts/fonts.css">
     and drop the two <link rel="preconnect" ...> lines.
  2. In sw.js: add "./fonts/fonts.css" and each "./fonts/<file>.woff2" to SHELL, bump CACHE.
NOTE
